package mtcls.common.helper;

import java.util.List;

import mtcls.common.model.AppModule;
import mtcls.common.model.AppNamespace;
import mtcls.common.model.AppProperty;
import mtcls.common.model.dto.AppModuleDto;
import mtcls.common.model.dto.AppNamespaceDto;
import mtcls.common.model.dto.AppPropertyDto;

public class MetadataHelper {
	public static final long 	ID_UNDEFINED = -1;
	public static final String 	AM_LABEL_DEFAULT = ""; 
	public static final String 	AM_GROUP_NAME_DEFAULT = ""; 
	public static final String 	AM_GROUP_LABEL_DEFAULT = "";
	public static final String 	AM_REPOSITORY_DEFAULT = "RepositoryWidget"; 
	public static final String 	AM_MODULE_WIDGET_DEFAULT = "ModuleWidget"; 
	public static final String 	AM_SEARCH_WIDGET_DEFAULT = "SearchWidget";
	public static final String 	AM_LIST_WIDGET_DEFAULT = "ListWidget"; 
	public static final String 	AM_DETAIL_WIDGET_DEFAULT = "DetailWidget"; 
	public static final boolean AM_EDITABLE_DEFAULT = true;
	public static final boolean AM_UPDATABLE_DEFAULT = true; 
	public static final boolean AM_CREATEABLE_DEFAULT = true; 
	public static final boolean AM_DUPLICATABLE_DEFAULT = true;
	public static final boolean AM_REMOVABLE_DEFAULT = true; 
	public static final boolean AM_AUDITABLE_DEFAULT = true; 
	public static final boolean AM_NAVIGATABLE_DEFAULT = true;
	public static final boolean AM_SEARCHABLE_DEFAULT = true; 
	public static final boolean AM_ADVANCED_SEARCHABLE_DEFAULT = true; 
	public static final boolean AM_LISTABLE_DEFAULT = true;
	public static final boolean AM_DETAILABLE_DEFAULT = true; 
	public static final String 	AP_GROUP_NAME_DEFAULT = ""; 
	public static final String 	AP_GROUP_LABEL_DEFAULT = ""; 
	public static final Object 	AP_VALUE_DEFAULT = null; 
	public static final String 	AP_SAVE_PARAMETERTYPE_DEFAULT = null;
	public static final Integer AP_WIDTH_DEFAULT = null;
	public static final Double 	AP_MIN_VALUE_DEFAULT = null; 
	public static final Double 	AP_MAX_VALUE_DEFAULT = null; 
	public static final String 	AP_REGEX_PATTERN_DEFAULT = null;
	public static final String 	AP_ADD_DEFAULT_VALUE_DEFAULT = null; 
	public static final String 	AP_EDIT_DEFAULT_VALUE_DEFAULT = null;
	public static final String 	AP_SEARCH_DEFAULT_VALUE_DEFAULT = null; 
	public static final String 	AP_LOOKUP_CRITERIA_DEFAULT = null;
	public static final String 	AP_LOOKUP_CRITERIA_PAIR_DEFAULT = null; 
	public static final String 	AP_LOOKUP_NAME_DEFAULT = null; 
	public static final String 	AP_LOOKUP_PAIR_DEFAULT = null;
	public static final String 	AP_REPOSITORY_DEFAULT = null; 
	public static final String 	AP_UPDATE_REPOSITORY_DEFAULT = null;
	public static final String 	AP_HISTORY_REPOSITORY_DEFAULT = null; 
	public static final Integer AP_DECIMAL_PRECISION_DEFAULT = null;
	public static final boolean AP_SORT_DESC_DEFAULT = false; 
	public static final boolean AP_KEY_DEFAULT = false; 
	public static final boolean AP_LOOKUP_DEFAULT = false; 
	public static final boolean AP_REQUIRED_DEFAULT = false;
	public static final boolean AP_SEARCHABLE_DEFAULT = false; 
	public static final boolean AP_SEARCH_RANGE_DEFAULT = false; 
	public static final boolean AP_SEARCH_PARTICIPATE_DEFAULT = true;
	public static final boolean AP_SEARCH_SHOW_ON_EMPTY_DEFAULT = true; 
	public static final boolean AP_LISTABLE_DEFAULT = true; 
	public static final boolean AP_DETAILABLE_DEFAULT = true;
	public static final boolean AP_ADVANCED_SEARCH_DEFAULT = true; 
	public static final boolean AP_EDITABLE_DEFAULT = true; 
	public static final boolean AP_EDITABLE_ON_ADD_DEFAULT = true;
	public static final boolean AP_EDITABLE_ON_SEARCH_DEFAULT = true; 
	public static final boolean AP_UPDATABLE_DEFAULT = true; 
	public static final boolean AP_DUPLICATABLE_DEFAULT = true;
	public static final boolean AP_HIDDEN_DEFAULT = false; 
	public static final boolean AP_UNIQUE_DEFAULT = false;
	
	public static AppNamespace createAppNamespace(String name){
		return new AppNamespaceDto(ID_UNDEFINED, name);
	}
	public static AppModule createAppModule(AppModule parentModule, 
							AppNamespace appNamespace, 
							String name,
							String label, 
							String groupName, 
							String groupLabel,
							String repository, 
							String moduleWidget, 
							String searchWidget,
							String listWidget, 
							String detailWidget, 
							boolean editable,
							boolean updatable, 
							boolean createable, 
							boolean duplicatable,
							boolean removable, 
							boolean auditable, 
							boolean navigatable,
							boolean searchable, 
							boolean advancedSearchable, 
							boolean listable,
							boolean detailable, 
							List<AppModule> childModules,
							List<AppProperty> properties){
		return new AppModuleDto(ID_UNDEFINED, 
								parentModule, 
								appNamespace, 
								name, 
								label, 
								groupName, 
								groupLabel, 
								repository, 
								moduleWidget, 
								searchWidget, 
								listWidget, 
								detailWidget, 
								editable, 
								updatable, 
								createable, 
								duplicatable, 
								removable, 
								auditable, 
								navigatable, 
								searchable, 
								advancedSearchable, 
								listable, 
								detailable, 
								childModules, 
								properties);
	}
	
	public static AppModule createDefaultModule(AppModule parentModule, 
							AppNamespace appNamespace, 
							String name,
							String label, 
							String groupName, 
							String groupLabel, 
							List<AppModule> childModules,
							List<AppProperty> properties){
		return createAppModule(parentModule, 
							appNamespace, 
							name, 
							label, 
							groupName, 
							groupLabel, 
							AM_REPOSITORY_DEFAULT, 
							AM_MODULE_WIDGET_DEFAULT, 
							AM_SEARCH_WIDGET_DEFAULT, 
							AM_LIST_WIDGET_DEFAULT, 
							AM_DETAIL_WIDGET_DEFAULT, 
							AM_EDITABLE_DEFAULT, 
							AM_UPDATABLE_DEFAULT, 
							AM_CREATEABLE_DEFAULT, 
							AM_DUPLICATABLE_DEFAULT, 
							AM_REMOVABLE_DEFAULT, 
							AM_AUDITABLE_DEFAULT, 
							AM_NAVIGATABLE_DEFAULT, 
							AM_SEARCHABLE_DEFAULT, 
							AM_ADVANCED_SEARCHABLE_DEFAULT, 
							AM_LISTABLE_DEFAULT, 
							AM_DETAILABLE_DEFAULT, 
							childModules, 
							properties);
	}
	
	public static AppProperty createAppProperty(String name, 
								String label, 
								Integer sequence,
								String groupName, 
								String groupLabel, 
								Integer sortPriority,
								String dataType, 
								String displayType, 
								String daoPropertyName,
								Object value, 
								String saveParameterType, 
								Integer width,
								Double minValue, 
								Double maxValue, 
								String regexPattern,
								String addDefaultValue, 
								String editDefaultValue,
								String searchDefaultValue, 
								String lookupCriteria,
								String lookupCriteriaPair, 
								String lookupName, 
								String lookupPair,
								String repository, 
								String updateRepository,
								String historyRepository, 
								Integer decimalPrecision,
								boolean sortDesc, 
								boolean key, 
								boolean lookup, 
								boolean required,
								boolean searchable, 
								boolean searchRange, 
								boolean searchParticipate,
								boolean searchShowOnEmpty, 
								boolean listable, 
								boolean detailable,
								boolean advancedSearch, 
								boolean editable, 
								boolean editableOnAdd,
								boolean editableOnSearch, 
								boolean updatable, 
								boolean duplicatable,
								boolean hidden, 
								boolean unique){
		return new AppPropertyDto(ID_UNDEFINED, 
								name, 	
								label, 
								sequence, 
								groupName, 
								groupLabel, 
								sortPriority, 
								dataType, 
								displayType, 
								daoPropertyName, 
								value, 
								saveParameterType, 
								width, 
								minValue, 
								maxValue, 
								regexPattern, 
								addDefaultValue, 
								editDefaultValue, 
								searchDefaultValue, 
								lookupCriteria, 
								lookupCriteriaPair, 
								lookupName, 
								lookupPair, 
								repository, 
								updateRepository, 
								historyRepository, 
								decimalPrecision, 
								sortDesc, 
								key, 
								lookup, 
								required, 
								searchable, 
								searchRange, 
								searchParticipate, 
								searchShowOnEmpty, 
								listable, 
								detailable, 
								advancedSearch, 
								editable, 
								editableOnAdd, 
								editableOnSearch, 
								updatable, 
								duplicatable, 
								hidden, 
								unique);
	}
	
	public static AppProperty createDefaultAppProperty(String name, 
			String label, 
			Integer sequence,
			String groupName, 
			String groupLabel, 
			Integer sortPriority,
			String dataType, 
			String displayType, 
			String daoPropertyName, 
			Integer width,
			Double minValue, 
			Double maxValue, 
			String regexPattern,
			String addDefaultValue, 
			String editDefaultValue,
			String searchDefaultValue, 
			String lookupCriteria,
			String lookupCriteriaPair, 
			String lookupName, 
			String lookupPair,
			Integer decimalPrecision,
			boolean sortDesc, 
			boolean key, 
			boolean lookup, 
			boolean required,
			boolean searchable, 
			boolean searchRange, 
			boolean advancedSearch, 
			boolean hidden, 
			boolean unique){
//		return new AppPropertyDto(ID_UNDEFINED,
		return createAppProperty(
				name, 	
				label, 
				sequence, 
				groupName, 
				groupLabel, 
				sortPriority, 
				dataType, 
				displayType, 
				daoPropertyName, 
				AP_VALUE_DEFAULT, 
				AP_SAVE_PARAMETERTYPE_DEFAULT,
				width, 
				minValue, 
				maxValue, 
				regexPattern, 
				addDefaultValue, 
				editDefaultValue, 
				searchDefaultValue, 
				lookupCriteria, 
				lookupCriteriaPair, 
				lookupName, 
				lookupPair, 
				AP_REPOSITORY_DEFAULT, 
				AP_UPDATE_REPOSITORY_DEFAULT, 
				AP_HISTORY_REPOSITORY_DEFAULT,  
				decimalPrecision, 
				sortDesc, 
				key, 
				lookup, 
				required, 
				searchable, 
				searchRange, 
				AP_SEARCH_PARTICIPATE_DEFAULT, 
				AP_SEARCH_SHOW_ON_EMPTY_DEFAULT, 
				AP_LISTABLE_DEFAULT, 
				AP_DETAILABLE_DEFAULT, 
				advancedSearch, 
				AP_EDITABLE_DEFAULT, 
				AP_EDITABLE_ON_ADD_DEFAULT, 
				AP_EDITABLE_ON_SEARCH_DEFAULT, 
				AP_UPDATABLE_DEFAULT, 
				AP_DUPLICATABLE_DEFAULT, 
				hidden, 
				unique);
	}
	
	public static AppProperty createDefaultStringProperty(String name, 
								String label, 
								Integer sequence,
								String groupName, 
								String groupLabel, 
								Integer sortPriority, 
								String daoPropertyName,
								Integer width,
								String regexPattern,
								String addDefaultValue, 
								String editDefaultValue,
								String searchDefaultValue, 
								boolean sortDesc, 
								boolean key, 
								boolean required, 
								boolean advancedSearch, 
								boolean unique){
		return createDefaultAppProperty(name, 
				label, 
				sequence,
				groupName, 
				groupLabel, 
				sortPriority,
				"String", 
				"Text", 
				daoPropertyName,
				width,
				AP_MIN_VALUE_DEFAULT, 
				AP_MAX_VALUE_DEFAULT, 
				regexPattern,
				addDefaultValue, 
				editDefaultValue,
				searchDefaultValue, 
				AP_LOOKUP_CRITERIA_DEFAULT, 
				AP_LOOKUP_CRITERIA_PAIR_DEFAULT, 
				AP_LOOKUP_NAME_DEFAULT, 
				AP_LOOKUP_PAIR_DEFAULT, 
				AP_DECIMAL_PRECISION_DEFAULT, 
				sortDesc, 
				key, 
				false, 
				required,
				true, 
				false, 
				advancedSearch, 
				false, 
				unique);
	}
	
	
	public static AppProperty createDefaultDateProperty(String name, 
			String label, 
			Integer sequence,
			String groupName, 
			String groupLabel, 
			Integer sortPriority, 
			String daoPropertyName,
			Integer width, 
			String regexPattern,
			String addDefaultValue, 
			String editDefaultValue,
			String searchDefaultValue, 
			boolean sortDesc, 
			boolean key, 
			boolean required,
			boolean searchRange, 
			boolean advancedSearch, 
			boolean unique){
		width = (width==null && regexPattern!=null) ? Integer.valueOf(regexPattern.length()) : null;
		return createDefaultAppProperty(name, 
				label, 
				sequence,
				groupName, 
				groupLabel, 
				sortPriority,
				"Date", 
				"Date", 
				daoPropertyName,
				width,
				AP_MIN_VALUE_DEFAULT, 
				AP_MAX_VALUE_DEFAULT, 
				regexPattern,
				addDefaultValue, 
				editDefaultValue,
				searchDefaultValue, 
				AP_LOOKUP_CRITERIA_DEFAULT, 
				AP_LOOKUP_CRITERIA_PAIR_DEFAULT, 
				AP_LOOKUP_NAME_DEFAULT, 
				AP_LOOKUP_PAIR_DEFAULT, 
				AP_DECIMAL_PRECISION_DEFAULT, 
				sortDesc, 
				key, 
				false, 
				required,
				true, 
				searchRange, 
				advancedSearch, 
				false, 
				unique);
	}
	
	public static AppProperty createDefaultRealNumberProperty(String name, 
			String label, 
			Integer sequence,
			String groupName, 
			String groupLabel, 
			Integer sortPriority, 
			String daoPropertyName, 
			Integer width,
			Double minValue, 
			Double maxValue, 
			String regexPattern,
			String addDefaultValue, 
			String editDefaultValue,
			String searchDefaultValue, 
			boolean sortDesc, 
			boolean key, 
			boolean required,
			boolean searchable, 
			boolean searchRange, 
			boolean advancedSearch, 
			boolean unique){
		return createDefaultAppProperty(name, 
				label, 
				sequence,
				groupName, 
				groupLabel, 
				sortPriority,
				"Number", 
				"Text", 
				daoPropertyName,
				width,
				minValue, 
				maxValue, 
				regexPattern,
				addDefaultValue, 
				editDefaultValue,
				searchDefaultValue, 
				AP_LOOKUP_CRITERIA_DEFAULT, 
				AP_LOOKUP_CRITERIA_PAIR_DEFAULT, 
				AP_LOOKUP_NAME_DEFAULT, 
				AP_LOOKUP_PAIR_DEFAULT, 
				AP_DECIMAL_PRECISION_DEFAULT, 
				sortDesc, 
				key, 
				false, 
				required,
				searchable, 
				searchRange, 
				advancedSearch, 
				false, 
				unique);
	}
	
	public static AppProperty createDefaultFloatNumberProperty(String name, 
			String label, 
			Integer sequence,
			String groupName, 
			String groupLabel, 
			Integer sortPriority,
			String daoPropertyName,
			Double minValue, 
			Double maxValue, 
			String regexPattern,
			String addDefaultValue, 
			String editDefaultValue,
			String searchDefaultValue, 
			Integer decimalPrecision,
			boolean sortDesc, 
			boolean key, 
			boolean required,
			boolean searchable, 
			boolean searchRange, 
			boolean advancedSearch, 
			boolean unique){
		return createDefaultAppProperty(name, 
				label, 
				sequence,
				groupName, 
				groupLabel, 
				sortPriority,
				"Number", 
				"Text", 
				daoPropertyName,
				null,
				minValue, 
				maxValue, 
				regexPattern,
				addDefaultValue, 
				editDefaultValue,
				searchDefaultValue, 
				AP_LOOKUP_CRITERIA_DEFAULT, 
				AP_LOOKUP_CRITERIA_PAIR_DEFAULT, 
				AP_LOOKUP_NAME_DEFAULT, 
				AP_LOOKUP_PAIR_DEFAULT, 
				decimalPrecision,
				sortDesc, 
				key, 
				false, 
				required,
				searchable, 
				searchRange, 
				advancedSearch, 
				false, 
				unique);
	}
	
	public static AppProperty createDefaultLookupProperty(String name, 
			String label, 
			Integer sequence,
			String groupName, 
			String groupLabel, 
			Integer sortPriority,
			String dataType, 
			String displayType, 
			String daoPropertyName,
			Object value, 
			String saveParameterType, 
			Integer width,
			Double minValue, 
			Double maxValue, 
			String addDefaultValue, 
			String editDefaultValue,
			String searchDefaultValue, 
			String lookupCriteria,
			String lookupCriteriaPair, 
			String lookupName, 
			String lookupPair,
			String repository, 
			String updateRepository,
			boolean sortDesc, 
			boolean key, 
			boolean required,
			boolean searchable, 
			boolean searchParticipate,
			boolean searchShowOnEmpty, 
			boolean listable, 
			boolean detailable,
			boolean advancedSearch, 
			boolean editable, 
			boolean editableOnAdd,
			boolean editableOnSearch, 
			boolean updatable, 
			boolean duplicatable,
			boolean unique){
		return createDefaultAppProperty(name, 
				label, 
				sequence,
				groupName, 
				groupLabel, 
				sortPriority,
				dataType, 
				displayType, 
				daoPropertyName,
				width,
				minValue, 
				maxValue, 
				null,
				addDefaultValue, 
				editDefaultValue,
				searchDefaultValue, 
				lookupCriteria,
				lookupCriteriaPair, 
				lookupName, 
				lookupPair,
				null,
				sortDesc, 
				key, 
				true, 
				required,
				searchable, 
				false, 
				advancedSearch, 
				false, 
				unique);
	}
}
